"""empty message

Revision ID: 7f29be3196c7
Revises: d959da4c652b
Create Date: 2017-12-28 21:55:42.076139

"""
from alembic import op
import sqlalchemy as sa
#6

# revision identifiers, used by Alembic.
revision = '7f29be3196c7'
down_revision = 'd959da4c652b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'create_time')
    # ### end Alembic commands ###
